# 1. Classification:

## Importing all required modules

In [16]:
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier

# Preparing dataset and spliting it into training and testing

In [6]:
dataset = pd.read_csv("heart-disease.csv")

X = dataset.drop("target", axis=1)
y = dataset["target"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Training and evaluating the model

In [8]:
clf = RandomForestClassifier(n_estimators=100)

clf.fit(X_train, y_train)

clf.score(X_test, y_test)

0.8688524590163934

# Making predictions using the trained model

#### 2-ways to make prediction:
1. predict()
2. predict_proba()

# 1. predict()

In [21]:
y_preds = clf.predict(X_test)

# Checking accuracy method-1:
np.mean(y_preds == y_test)

np.float64(0.8688524590163934)

In [23]:
# checking accuracy method-2:
from sklearn.metrics import accuracy_score

accuracy_score(y_test, y_preds)

0.8688524590163934

In [24]:
# checking accuracy method-3:
clf.score(X_test, y_test)

0.8688524590163934

# 2. predict_proba()

It returns the probabilities of a classification label

In [26]:
clf.predict_proba(X_test[:10])

array([[0.07, 0.93],
       [0.7 , 0.3 ],
       [0.5 , 0.5 ],
       [0.96, 0.04],
       [0.75, 0.25],
       [0.26, 0.74],
       [0.82, 0.18],
       [0.82, 0.18],
       [0.85, 0.15],
       [0.03, 0.97]])

In [27]:
clf.predict(X)

array([1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0])

# 2. Regression:

## Importing all required modules

In [28]:
from sklearn.model_selection import train_test_split
from sklearn.datasets import fetch_california_housing
import pandas as pd
from sklearn.ensemble import RandomForestRegressor

## Fetching, framing and splitting data

In [29]:
dataset = fetch_california_housing()
dataset

{'data': array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
           37.88      , -122.23      ],
        [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
           37.86      , -122.22      ],
        [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
           37.85      , -122.24      ],
        ...,
        [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
           39.43      , -121.22      ],
        [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
           39.43      , -121.32      ],
        [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
           39.37      , -121.24      ]]),
 'target': array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894]),
 'frame': None,
 'target_names': ['MedHouseVal'],
 'feature_names': ['MedInc',
  'HouseAge',
  'AveRooms',
  'AveBedrms',
  'Population',
  'AveOccup',
  'Latitude',
  'Longitude'],
 'DESCR': '.. _california_housing_dataset:\n

In [34]:
housing_dataset = pd.DataFrame(dataset["data"], columns=dataset["feature_names"])
housing_dataset["MedHouseVal"] = dataset['target']
housing_dataset

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0      8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1      8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2      7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3      5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4      3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   
...       ...       ...       ...        ...         ...       ...       ...   
20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48   
20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49   
20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43   
20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43   
20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37   

       Longitude  MedHouseVal  
0        -122.23        4.526  
1        -122.22        3.585  
2        -122.24        3.521  
3        -122.25        3.413  
4        -122.25        3.422  
...          ...          ...  
20635    -121.09        0.781  
20636    -121.21        0.771  
20637    -121.22        0.923  
20638    -121.32        0.847  
20639    -121.24        0.894  

[20640 rows x 9 columns]

In [35]:
X = housing_dataset.drop("MedHouseVal", axis=1)
y = housing_dataset["MedHouseVal"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

## Fitting the data and training the model

In [37]:
model = RandomForestRegressor(n_estimators=100)
model.fit(X_train, y_train)

y_preds = model.predict(X_test)
y_preds[:10]

array([1.55867  , 1.9098001, 1.7821701, 3.1054   , 3.2933603, 4.3782322,
       0.86238  , 1.07616  , 0.95937  , 1.27869  ])

## Comparing the predicitions with the true values

In [38]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_test, y_preds)

np.float64(0.32250405058139553)